### ISSUE TITLE
Is this rule like `no-restricted-syntax`?

### ISSUE THREAD

**Issue by fisker** [brettz9/eslint-plugin-query#1]
https://eslint.org/docs/rules/no-restricted-syntax

**Comment by brettz9** [comment]
I've since added a screenshot with results (showing the actual discovered functions (truncated)).

Btw, in case you were interested, regarding the side discussion at https://github.com/sindresorhus/eslint-plugin-unicorn/issues/144 , I since discovered that sindresorhus also has the [`globals`](https://www.npmjs.com/package/globals) package so I was thinking a separate repo might use it to whitelist `dom` and then the only globals allowed would be DOM building ones (e.g., `document`, `HTMLElement`, etc., though `window` should need extra handling as `window.PaymentRequest()` is just as bad as `PaymentRequest()`). I'm discovered that `eslint-plugin-import` has some rules like `no-nodejs-modules` which would also really help in restricting undue privileges out of imported third-party npm packages. I've added https://github.com/brettz9/eslint-plugin-privileges with some notes in case I may find time to collect all of this together and develop it further, and you'd also be most welcome to join in there if it interests you.
